version: '3'
services:
  desktop:
    image: dockerenv:latest
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - PASSWORD=000000
    container_name: dockerenv
    restart: always
    privileged: true
    # environment:
    #   - PASSWORD=123456
    ports:
      - "8000:22"
      # - "7890:7890"
      # - "9090:9090"
      - "5901:5901"
      - "6081:6081"
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]