version: '3.7'
networks:
  net:
    driver: bridge
services:
  clash-server:
    image: dreamacro/clash
    container_name: clash
    ports:
      - "7890:7890"
      - "7891:7891"
      - "9090:9090"
    volumes:
      - ./config.yaml:/root/.config/clash/config.yaml
    networks:
      - net
  clash-ui:
    image: haishanh/yacd
    container_name: clash-ui
    ports:
      - 8080:80
    networks:
      - net