version: '3'
services:
  desktop:
    image: dockerenv:latest
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: dockerenv
    restart: always
    privileged: true
    environment:
      - USER=${USER:-root}
      - PASSWORD=${PASSWORD:-123456}
    ports:
      - "8400:22"
      - "8401:5901"
      - "8402:6081"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]